REPORT ZMATERIAL_REPORT.

TABLES: MARA.

DATA: lt_mara TYPE TABLE OF MARA.

SELECT * FROM MARA INTO TABLE lt_mara UP TO 10 ROWS.

LOOP AT lt_mara INTO DATA(ls_mara).
  WRITE: / ls_mara-MATNR, ls_mara-MTART, ls_mara-MBRSH.
ENDLOOP.
